#阿里云对象存储OSS配置
aliYun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    accesskeyId: LTAIdlXOe01k4AE6
    accesskeySecret: mIQJ8U0kzqEekHpWNPZuHMaGC4q9tz
    bucketName: wushengjie
    dir: blog/img/
#邮件配置
mail:
  host: smtp.163.com
  port: 465
  username: fjfjfj0851
  password: fjfjfj0851
  from: fjfjfj0851@163.com
  to: fjfjfj0851@163.com
#spring配置
spring:
  #数据源
  datasource:
    url: jdbc:mysql://119.23.214.174:3306/blog
    username: bloguser
    password: fjfjfj
    driver-class-name: com.mysql.jdbc.Driver
  #thymeleaf
  thymeleaf:
    cache: false
    #启用不严格检查html
    mode: LEGACYHTML5

#加载log4j2
logging:
  config: classpath:log4j2.xml
  level: debug
  file:
server:
  session-timeout : 3600
  port: 8088