#spring配置
spring:
  #数据源
  datasource:
    url: jdbc:mysql://119.23.214.174:3306/blog
    username: bloguser
    password: fjfjfj
    driver-class-name: com.mysql.jdbc.Driver
  #thymeleaf
  thymeleaf:
    #启用不严格检查html
    mode: LEGACYHTML5
    cache: false
#加载log4j2
logging:
  config: classpath:log4j2.xml
  level: debug
  file: