-- auto Generated on 2017-07-14 15:03:09
-- DROP TABLE IF EXISTS ARTICLE_TAGS;
CREATE TABLE ARTICLE_TAGS(
    ARTICLE_ID INT (11) NOT NULL DEFAULT -1 COMMENT 'articleId',
    TAG_ID INT (11) NOT NULL DEFAULT -1 COMMENT 'tagId',
    ID INT (11) NOT NULL AUTO_INCREMENT COMMENT 'id',
    CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'createTime',
    INDEX(ID),
    PRIMARY KEY (ID)
)ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT 'ARTICLE_TAGS';
