-- auto Generated on 2017-07-09 15:40:47 
-- DROP TABLE IF EXISTS `ARTICLE`; 
CREATE TABLE `ARTICLE` (
    `CATEGORY_ID` int(11) NOT NULL DEFAULT '-1' COMMENT 'categoryId',
    `TITLE` varchar(50) NOT NULL DEFAULT '' COMMENT 'title',
    `CONTENT` longtext COMMENT 'content',
    `DESCRIPTION` varchar(50) DEFAULT '' COMMENT 'description',
    `STATUS` int(11) NOT NULL DEFAULT '0' COMMENT 'status',
    `AUTHOR` varchar(50) DEFAULT '' COMMENT 'author',
    `UPDATE_TIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updateTime',
    `SHOW_COUNT` int(11) NOT NULL DEFAULT '0' COMMENT 'showCount',
    `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'id',
    `CREATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'createTime',
    PRIMARY KEY (`ID`),
    KEY `ID` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8 COMMENT='`ARTICLE`';
