-- auto Generated on 2017-07-09 02:29:46 
-- DROP TABLE IF EXISTS `LINK`; 
CREATE TABLE `LINK`(
    `NAME` VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'name',
    `URL` VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'url',
    `DESC` VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'desc',
    `SORT` INT (11) NOT NULL DEFAULT -1 COMMENT 'sort',
    `ID` INT (11) NOT NULL AUTO_INCREMENT COMMENT 'id',
    `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'createTime',
    INDEX(ID),
    PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '`LINK`';
