-- auto Generated on 2017-07-09 02:13:06 
-- DROP TABLE IF EXISTS `TAG`; 
CREATE TABLE `TAG`(
    `NAME` VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'name',
    `ID` INT (11) NOT NULL AUTO_INCREMENT COMMENT 'id',
    `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'createTime',
    INDEX(ID),
    PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '`TAG`';
