-- auto Generated on 2017-07-07 19:10:07 
-- DROP TABLE IF EXISTS `USER`; 
CREATE TABLE `USER`(
    `LOGIN_NAME` VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'loginName',
    `USER_NAME` VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'userName',
    `PASSWORD` VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'password',
    `EXPIRED` TINYINT (3) NOT NULL DEFAULT 0 COMMENT 'expired',
    `LOCKED` TINYINT (3) NOT NULL DEFAULT 0 COMMENT 'locked',
    `ENABLED` TINYINT (3) NOT NULL DEFAULT 0 COMMENT 'enabled',
    `ID` INT (11) NOT NULL AUTO_INCREMENT COMMENT 'id',
    `CREATE_TIME` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'createTime',
    INDEX(ID),
    PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '`USER`';
